# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk16

# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN="2591f87e-8612-481b-8bdf-ec808130a36f"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -YavorskiE@Outlook.com
    on_success: never # default: change
    on_failure: always # default: always
